/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sesion2.vista;

import com.sesion2.utilidades.LimpiarComponentes;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author abarrios
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setTitle("Mi Calculadora");
        this.setLocationRelativeTo(null);
        this.setExtendedState(3);
        //this.setSize(350, 350);
        //Image image = new ImageIcon(getClass().getResource("/com/sesion2/iconos/calculadora.png")).getImage();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/sesion2/iconos/calculadora.png"));
        this.setIconImage(iconoPropio);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("./com/sesion2/iconos/calculadora.png"));

        return retValue;
    }

    //Aquí se programa
    private void ejecutarCalculadoraProfesional() {
        //Obtener los valores de los JTextField

        String primerValorString = this.txtPrimerValor.getText().trim(); //trim() me retorna el texto sin espacios vacíos adelante y atrás
        String segundoValorString = this.txtSegundoValor.getText().trim();

        //Si ambos valores están vacíos
        if (primerValorString.equals("") || primerValorString.isEmpty() || segundoValorString.equals("") || segundoValorString.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No deben ir campos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            double primerValor = Double.parseDouble(primerValorString);
            double segundoValor = Double.parseDouble(segundoValorString);

            //Obtener la posición
            int accion = this.cbxAccion.getSelectedIndex();

            double resultado = 0;

            if (accion == 0) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una opción", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else if (accion == 1) { //Suma.
                resultado = primerValor + segundoValor;
                this.lblResultado.setText(String.valueOf(resultado));
                this.limpiar();
            } else if (accion == 2) { //Resta.
                resultado = primerValor - segundoValor;
                this.lblResultado.setText(String.valueOf(resultado));
                this.limpiar();
            } else if (accion == 3) { //Multiplicación.
                resultado = primerValor * segundoValor;
                this.lblResultado.setText(String.valueOf(resultado));
                this.limpiar();
            } else if (accion == 4) { //División Entera.
                if (segundoValor == 0) {
                    //Error.
                    JOptionPane.showMessageDialog(null, "No se puede dividir entre cero", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    resultado = primerValor / segundoValor;
                    this.lblResultado.setText(String.valueOf(resultado));
                    this.limpiar();
                }

            } else if (accion == 5) { //División Residuo.
                resultado = primerValor % segundoValor;
                this.lblResultado.setText(String.valueOf(resultado));
                this.limpiar();
            }

        }
    }

    private void limpiar() {
        LimpiarComponentes.limpiarComponentes(this.pnlMiCalculadora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMiCalculadora = new javax.swing.JPanel();
        lblMiCalculadora = new javax.swing.JLabel();
        lblPrimerValor = new javax.swing.JLabel();
        lblSegundoValor = new javax.swing.JLabel();
        txtPrimerValor = new javax.swing.JTextField();
        txtSegundoValor = new javax.swing.JTextField();
        lblAccion = new javax.swing.JLabel();
        cbxAccion = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        lblResultadoEs = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        pnlMiCalculadora.setBackground(new java.awt.Color(255, 255, 255));

        lblMiCalculadora.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblMiCalculadora.setForeground(new java.awt.Color(0, 0, 102));
        lblMiCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiCalculadora.setText("Mi Calculadora");

        lblPrimerValor.setText("Primer Valor:");

        lblSegundoValor.setText("Segundo Valor:");

        lblAccion.setText("Acción:");

        cbxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Suma", "Resta", "Multiplicación", "Divisón Entera", "División Residuo" }));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sesion2/iconos/calculate.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultadoEs.setText("El resultado es: ");

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sesion2/iconos/clear.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMiCalculadoraLayout = new javax.swing.GroupLayout(pnlMiCalculadora);
        pnlMiCalculadora.setLayout(pnlMiCalculadoraLayout);
        pnlMiCalculadoraLayout.setHorizontalGroup(
            pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiCalculadoraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegundoValor)
                    .addComponent(lblPrimerValor)
                    .addComponent(lblResultadoEs)
                    .addComponent(lblAccion))
                .addGap(35, 35, 35)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMiCalculadoraLayout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnLimpiar))
                    .addComponent(txtPrimerValor)
                    .addComponent(txtSegundoValor)
                    .addComponent(cbxAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMiCalculadoraLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblMiCalculadora)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlMiCalculadoraLayout.setVerticalGroup(
            pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiCalculadoraLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblMiCalculadora)
                .addGap(32, 32, 32)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerValor)
                    .addComponent(txtPrimerValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoValor)
                    .addComponent(txtSegundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccion))
                .addGap(18, 18, 18)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(pnlMiCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoEs)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMiCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMiCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        this.ejecutarCalculadoraProfesional();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbxAccion;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblMiCalculadora;
    private javax.swing.JLabel lblPrimerValor;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultadoEs;
    private javax.swing.JLabel lblSegundoValor;
    private javax.swing.JPanel pnlMiCalculadora;
    private javax.swing.JTextField txtPrimerValor;
    private javax.swing.JTextField txtSegundoValor;
    // End of variables declaration//GEN-END:variables
}
