/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sesion3.vista;

import com.sesion3.Sesion3;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author abarrios
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        //Aquí se ponen los métodos para iniciar el programa
        this.setTitle("Vista");
        this.setLocationRelativeTo(null);
        this.setExtendedState(3);
        //Que esté seleccionado por defecto PHP
        this.radioPHP.setSelected(true);
        //Llena el ComboBox
        this.llenarComboBox();
    }
    
    private void llenarComboBox() {
        //Definimos un arreglo tipo String con datos lenguajes de programación
        String[] lenguajes = new String[]{"Seleccione...", "PHP", "Java", "C++", "Pyhton"};

        //Libreria de modelo para el ComboBox, el modelo es el contenido del ComboBox
        //Asignando el arreglo a mi modelo de ComboBox
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(lenguajes);
        //Asignar este modelo a nuestro ComboBox
        this.cbxLenguajes.setModel(modelo);
    }
    
    private void cambiarModelo() {
        String[] basesDatos = new String[]{"Seleccione...", "Oracle", "MySQL", "SQLite", "Postgres"};
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(basesDatos);
        this.cbxLenguajes.setModel(modelo);
    }

    //Aquí se programa
    private void validarRadios() {
        if (this.radio1.isSelected()) {
            this.radio2.setSelected(false);
            this.radio3.setSelected(false);
        } else if (this.radio2.isSelected()) {
            this.radio1.setSelected(false);
            this.radio3.setSelected(false);
        } else if (this.radio3.isSelected()) {
            this.radio1.setSelected(false);
            this.radio2.setSelected(false);
        }
    }
    
    private void saludar() {
        Sesion3 sesion3 = new Sesion3();
        String saludo = sesion3.retornarSaludo();
        this.txtSaludo.setText(saludo);
    }
    
    private void validar() {
        //Saber si el Check está activado
        if (this.checkValidar.isSelected()) {
            //Doble validación
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Realmente, a pesar de no haber leído los términos y condiciones, los va a aceptar?");
            if (respuesta == 0) {
                //Enviar a la otra pantalla
                Pantalla pantalla = new Pantalla(); //Crear instancia
                pantalla.setVisible(true); //Hacer visible la pantalla
                this.dispose(); //Cerrar la pantalla actual
            } else {
                JOptionPane.showMessageDialog(null, "OK, no!");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Por favor acepte los términos y condiciones", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoColores = new javax.swing.ButtonGroup();
        grupoLenguajes = new javax.swing.ButtonGroup();
        pnlVista = new javax.swing.JPanel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radioPHP = new javax.swing.JRadioButton();
        radioJava = new javax.swing.JRadioButton();
        radioPython = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        btnSaludar = new javax.swing.JButton();
        txtSaludo = new javax.swing.JTextField();
        checkValidar = new javax.swing.JCheckBox();
        btnValidar = new javax.swing.JButton();
        cbxLenguajes = new javax.swing.JComboBox<>();
        btnCambiarModelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoColores.add(radio1);
        radio1.setSelected(true);
        radio1.setText("Amarillo");

        grupoColores.add(radio2);
        radio2.setText("Azul");

        grupoColores.add(radio3);
        radio3.setText("Rojo");

        grupoLenguajes.add(radioPHP);
        radioPHP.setText("PHP");

        grupoLenguajes.add(radioJava);
        radioJava.setText("Java");

        grupoLenguajes.add(radioPython);
        radioPython.setText("Python");

        grupoLenguajes.add(radioC);
        radioC.setText("C++");

        btnSaludar.setText("Saludar");
        btnSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaludarActionPerformed(evt);
            }
        });

        checkValidar.setText("A pesar de no haber leido, igual acepto las políticas y privacidades");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnCambiarModelo.setText("Cambiar Modelo");
        btnCambiarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVistaLayout = new javax.swing.GroupLayout(pnlVista);
        pnlVista.setLayout(pnlVistaLayout);
        pnlVistaLayout.setHorizontalGroup(
            pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVistaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVistaLayout.createSequentialGroup()
                        .addComponent(txtSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(536, Short.MAX_VALUE))
                    .addGroup(pnlVistaLayout.createSequentialGroup()
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio1)
                            .addComponent(radio2)
                            .addComponent(radio3)
                            .addComponent(btnSaludar))
                        .addGap(70, 70, 70)
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioPHP)
                            .addComponent(radioC)
                            .addComponent(radioPython)
                            .addComponent(radioJava))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambiarModelo)
                            .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnValidar)
                                .addComponent(cbxLenguajes, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlVistaLayout.setVerticalGroup(
            pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVistaLayout.createSequentialGroup()
                .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVistaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio1)
                            .addComponent(radioPHP))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioJava, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radio2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio3)
                            .addComponent(radioPython))
                        .addGroup(pnlVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVistaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioC))
                            .addGroup(pnlVistaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnSaludar)))
                        .addGap(18, 18, 18)
                        .addComponent(txtSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVistaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(checkValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnValidar)
                        .addGap(12, 12, 12)
                        .addComponent(btnCambiarModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxLenguajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaludarActionPerformed
        // TODO add your handling code here:
        this.saludar();
    }//GEN-LAST:event_btnSaludarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        this.validar();
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnCambiarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarModeloActionPerformed
        // TODO add your handling code here:
        this.cambiarModelo();
    }//GEN-LAST:event_btnCambiarModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarModelo;
    private javax.swing.JButton btnSaludar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox<String> cbxLenguajes;
    private javax.swing.JCheckBox checkValidar;
    private javax.swing.ButtonGroup grupoColores;
    private javax.swing.ButtonGroup grupoLenguajes;
    private javax.swing.JPanel pnlVista;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioJava;
    private javax.swing.JRadioButton radioPHP;
    private javax.swing.JRadioButton radioPython;
    private javax.swing.JTextField txtSaludo;
    // End of variables declaration//GEN-END:variables
}
