/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sesion6.vistas;

import com.sesion6.entidades.Vehiculo;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abarrios
 */
public class VistaVehiculo extends javax.swing.JFrame {

    //Modelos
    //Modelo Marca Vehiculo
    //private String[] marcas = new String[]{"Seleccione...", "Audi", "Toyota", "Nissan", "Chevrolet", "Mazda", "Hyundai"};
    private String[] marcas = new String[]{"Seleccione...", "Audi", "Toyota", "Nissan"};
    private DefaultComboBoxModel mcbMarca = new DefaultComboBoxModel(this.marcas); //Definimos nuestro modelo del combo
    //Modelo Modelo Vehículo
    private String[] modelos = new String[]{"Seleccione...", "A1", "A3", "A4"};
    private DefaultComboBoxModel mcbModelo = new DefaultComboBoxModel(this.modelos);
    //Modelo Color Vehículo
    //private String[] colores = new String[]{"Seleccione...", "Blanco", "Negro", "Rojo", "Azul", "Amarillo", "Verde", "Rosa", "Gris", "Marrón", "Púrpura"};
    private String[] colores = new String[]{"Seleccione...", "Negro", "Rojo", "Azul"};
    private DefaultComboBoxModel mcbColor = new DefaultComboBoxModel(this.colores);

    //Modelo Tabla Vehículos
    private String[] columnas = new String[]{"Marca", "Modelo", "Color", "Año", "Fecha", "Precio"};
    private DefaultTableModel modeloTabla = new DefaultTableModel(this.columnas, 0);

    //Objetos
    private Vehiculo vehiculo = new Vehiculo();

    /**
     * Creates new form VistaVehiculo
     */
    public VistaVehiculo() {
        initComponents();
        this.setTitle("Vehículos");
        this.setLocationRelativeTo(null);
        this.setExtendedState(3);
        this.cbxMarca.setModel(this.mcbMarca);
        this.cbxModelo.setModel(this.mcbModelo);
        this.cbxColor.setModel(this.mcbColor);
        this.jDateFecha.setDate(new Date());
        this.tblVehiculos.setModel(this.modeloTabla);
    }

    private void validarMarcas() {
        int marca = this.cbxMarca.getSelectedIndex();

        switch (marca) {
            case 0:
                JOptionPane.showMessageDialog(null, "Debe seleccionar una opción", "Advertencia", JOptionPane.WARNING_MESSAGE);
                break;

            case 1:
                //A1, A3, A4
                String[] modelosAudi = new String[]{"Seleccione...", "A1", "A3", "A4"};
                this.mcbModelo = new DefaultComboBoxModel(modelosAudi);
                this.cbxModelo.setModel(this.mcbModelo);
                break;

            case 2:
                String[] modelosToyota = new String[]{"Seleccione...", "Toyota 4Runner", "Toyota Agya", "Toyota Avanza"};
                this.mcbModelo = new DefaultComboBoxModel(modelosToyota);
                this.cbxModelo.setModel(this.mcbModelo);
                break;

            case 3:
                String[] modelosNissan = new String[]{"Seleccione...", "370Z", "Ariya", "Evalia"};
                this.mcbModelo = new DefaultComboBoxModel(modelosNissan);
                this.cbxModelo.setModel(this.mcbModelo);
                break;

            default:
                JOptionPane.showMessageDialog(null, "Opción NO válida", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private void guardar() {
        String marca = this.cbxMarca.getSelectedItem().toString();
        String modelo = this.cbxModelo.getSelectedItem().toString();
        String color = this.cbxColor.getSelectedItem().toString();
        int anio = this.jDateAnio.getYear();
        Date fecha = this.jDateFecha.getDate();
        SimpleDateFormat formatoNuevo = new SimpleDateFormat("dd/MM/YYYY");
        String fechaFormateada = formatoNuevo.format(fecha);
        System.out.println("La fecha es: " + fechaFormateada);

        double precio = Double.parseDouble(this.txtPrecio.getText());

        //Seteamos
        this.vehiculo.setMarca(marca);
        this.vehiculo.setModelo(modelo);
        this.vehiculo.setColor(color);
        this.vehiculo.setAnio(anio);
        this.vehiculo.setFecha(fechaFormateada);
        this.vehiculo.setPrecio(precio);

        //Lista en la tabla
        Object[] filas = new Object[]{this.vehiculo.getMarca(), this.vehiculo.getModelo(), this.vehiculo.getColor(), this.vehiculo.getAnio(), this.vehiculo.getFecha(), this.vehiculo.getPrecio()};
        this.modeloTabla.addRow(filas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVehiculos = new javax.swing.JPanel();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        lblVehiculos = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxModelo = new javax.swing.JComboBox<>();
        cbxColor = new javax.swing.JComboBox<>();
        lblAnio = new javax.swing.JLabel();
        lblFechaConsulta = new javax.swing.JLabel();
        jDateAnio = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlVehiculos.add(jDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, 30));

        lblVehiculos.setText("Vehículos");
        pnlVehiculos.add(lblVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        lblMarca.setText("Marca:");
        pnlVehiculos.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblModelo.setText("Modelo:");
        pnlVehiculos.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblColor.setText("Color:");
        pnlVehiculos.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cbxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });
        pnlVehiculos.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, -1));

        cbxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlVehiculos.add(cbxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, -1));

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlVehiculos.add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, -1));

        lblAnio.setText("Año:");
        pnlVehiculos.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblFechaConsulta.setText("Fecha de Consulta:");
        pnlVehiculos.add(lblFechaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        pnlVehiculos.add(jDateAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 70, -1));

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        pnlVehiculos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 570, 250));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlVehiculos.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        lblPrecio.setText("Precio");
        pnlVehiculos.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        pnlVehiculos.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        // TODO add your handling code here:
        this.validarMarcas();
    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VistaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxModelo;
    private com.toedter.calendar.JYearChooser jDateAnio;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFechaConsulta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JPanel pnlVehiculos;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
